malloc_bench: Use stdext::expected
Added a new function that will print the string of an errno, that this is used in multiple places. The function is called `perror`. Even though the name `strerror` might be more appropriate, this tickles a bug in clang-tidy on Ubuntu 24.04:

Error running '/usr/bin/clang-tidy': PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
 0.      Program arguments: /usr/bin/clang-tidy --extra-arg-before=--driver-mode=g++ /source/qnx/tools/core_latency/core_benchmark.cpp -- /usr/bin/clang++ -I/source/qnx/lib/libubench/include -I/source/qnx/lib/libstdext/include -I/build/tools/core_latency -Qunused-arguments -rtlib=compiler-rt -stdlib=libc++ -O3 -DNDEBUG -std=c++17 -MD -MT tools/core_latency/CMakeFiles/core_latency.dir/core_benchmark.cpp.o -MF CMakeFiles/core_latency.dir/core_benchmark.cpp.o.d -o CMakeFiles/core_latency.dir/core_benchmark.cpp.o -c /source/qnx/tools/core_latency/core_benchmark.cpp
 1.      <eof> parser at end of file
 2.      While analyzing stack:
         #0 Calling core_benchmark::run(std::uint32_t, std::uint32_t)::(anonymous class)::operator()()
 3.      /source/qnx/tools/core_latency/core_benchmark.cpp:210:20: Error evaluating statement
 4.      /source/qnx/tools/core_latency/core_benchmark.cpp:210:20: Error evaluating statement
 #0 0x000079a2b25663bf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-18/bin/../lib/libLLVM.so.18.1+0xda63bf)
 #1 0x000079a2b25644f9 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-18/bin/../lib/libLLVM.so.18.1+0xda44f9)
 #2 0x000079a2b2566b00 (/usr/lib/llvm-18/bin/../lib/libLLVM.so.18.1+0xda6b00)
 #3 0x000079a2b1288320 (/lib/x86_64-linux-gnu/libc.so.6+0x45320)
 #4 0x000079a2bbad95f0 clang::ento::MemRegion::getBaseRegion() const (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2d0e5f0)
 #5 0x000079a2bbc6255a (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2e9755a)
 #6 0x000079a2bbc665d3 (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2e9b5d3)
 #7 0x000079a2bba789b0 clang::ento::CheckerManager::runCheckersForCallEvent(bool, clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&, clang::ento::CallEvent const&, clang::ento::ExprEngine&, bool) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cad9b0)
 #8 0x000079a2bbac05ef clang::ento::ExprEngine::evalCall(clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNode*, clang::ento::CallEvent const&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cf55ef)
 #9 0x000079a2bbac02a7 clang::ento::ExprEngine::VisitCallExpr(clang::CallExpr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cf52a7)
 #10 0x000079a2bba9fa12 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cd4a12)
 #11 0x000079a2bba9be7a clang::ento::ExprEngine::ProcessStmt(clang::Stmt const*, clang::ento::ExplodedNode*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cd0e7a)
 #12 0x000079a2bba9bbb8 clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cd0bb8)
 #13 0x000079a2bba82418 clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cb7418)
 #14 0x000079a2bba81f6c clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2cb6f6c)
 #15 0x000079a2bbe9f529 (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x30d4529)
 #16 0x000079a2bbe7f51f (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x30b451f)
 #17 0x000079a2bb80dfbc clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2a42fbc)
 #18 0x000079a2b99623d6 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xb973d6)
 #19 0x000079a2bb7d162c clang::FrontendAction::Execute() (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2a0662c)
 #20 0x000079a2bb74e0b4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x29830b4)
 #21 0x000079a2bb9c56b9 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2bfa6b9)
 #22 0x000058371909fab3 (/usr/bin/clang-tidy+0x1383ab3)
 #23 0x000079a2bb9c5414 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2bfa414)
 #24 0x000079a2bb9c417f clang::tooling::ToolInvocation::run() (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2bf917f)
 #25 0x000079a2bb9c71c1 clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2bfc1c1)
 #26 0x000058371909bd9b clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef) (/usr/bin/clang-tidy+0x137fd9b)
 #27 0x000058371841bc65 clang::tidy::clangTidyMain(int, char const**) (/usr/bin/clang-tidy+0x6ffc65)
 #28 0x000079a2b126d1ca (/lib/x86_64-linux-gnu/libc.so.6+0x2a1ca)
 #29 0x000079a2b126d28b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28b)
 #30 0x0000583718416fe5 _start (/usr/bin/clang-tidy+0x6fafe5)

i.e. the usage of `std::cout << ubench::string::strerror(errno)` it crashes reliably. Change it to `std::cout << ubench:string:perror(errno)` it works. The bug is not on later versions of clang-tidy.

Issue: OSDEV-75